export const CHANGE_CONTENT_BY_FILE_NAME = 'CHANGE_CONTENT_BY_FILE_NAME';
export const CREATE_NEW_FILE = 'CREATE_NEW_FILE';
export const DELETE_FILE = 'DELETE_FILE';
export const CHANGE_FILE_NAME = 'CHANGE_FILE_NAME';
